name: linting

on: [push]

jobs: 
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check for linting in electron
      run: |
        cd electron
        npm install
        npm run lintnf

